# This GitHub Actions script is adapted from czoins/innoextract

name: Build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "dscharrer/innoextract"

      - name: Setup Environment
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-zlib mingw-w64-x86_64-bzip2 mingw-w64-x86_64-xz

      - name: Build
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: |
          mkdir build
          cd build
          # Remove DLL import lib to force static linking of bzip2
          rm $MSYS2_LOCATION/mingw64/lib/libbz2.dll.a
          cmake -G"MinGW Makefiles" -DUSE_LTO=OFF -DCMAKE_EXE_LINKER_FLAGS=-static -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=ON ..
          mingw32-make -j8
          strip innoextract.exe

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Release files
        shell: cmd
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: |
          mkdir build\release
          xcopy "build\innoextract.exe" "build\release" /Y
          xcopy "%MSYS2_LOCATION%\mingw64\bin\*.dll" "build\release" /Y
          upx --ultra-brute --lzma .\build\innoextract.exe
          powershell -c "Compress-Archive -Path .\build\innoextract.exe -DestinationPath innoextract-windows.zip"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: innoextract
          path: innoextract-windows.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: innoextract-windows.zip
